# python 4

12. File I/O(파일 입출력)  

파일 입출력은 다양하게 많이 쓰입니다.   
예를 들면 엑셀 파일 같은 것들을 읽어들일 때나 텍스트 파일에서  
원하는 문자열을 추출할 때 등등 꼭 짚고 넘어가는 것이 일반적입니다.

아래의 코드로 설명을 시작해보도록 하겠습니다.
```
f = open("filename.txt", 'w')
f.write("이 문자열은 파일에 기록됩니다.")
f.close()
```
> 파일 객체 = open(파일 이름, 모드)  

모드의 종류에는 3가지가 있습니다.

모드	설명  
r	읽기 모드 - 파일을 읽어들일 때 사용함  
w	쓰기 모드 - 파일에 내용을 쓸 때 사용함  
a	추가 모드 - 파일의 끝에 새로운 내용을 추가할 때 사용함  
요렇게 3가지로 분류할 수 있습니다.  

w 모드로 열게 되면 해당 파일이 이미 존재하면  
원래 있던 내용을 다 지워지고 새로 작성됩니다. 또한 해당 파일이  
없을 경우 새로 생성을 하게 됩니다.

### w 모드 예제
```
f = open("example.txt", 'w')
for i in range(1, 6): # 1 이상부터 6 미만까지
    data = "%d번째 줄입니다.\n" % i
    f.write(data)
f.close()
```
1 이상부터 6 미만까지의 리스트를 range 메서드로  
생성해서 1부터 5까지의 숫자가 i에 들어가면서 파일에 쓰여진다.

### r 모드 예제
```
f = open("example.txt", 'r')
data = f.read()
print(data)
f.close()
```
파일을 전부 문자열로 리턴하는 read 메서드를 사용해서 파일 전체를 읽어들일 수 있다.

### a 모드 예제
```
f = open("example.txt",'a')
for i in range(6, 11):
    data = "%d번째 줄입니다.\n" % i
    f.write(data)
f.close()
```
요렇게 example.txt 뒤에 추가해줄 수 있습니다.

그리고 추가적인 부분을 살펴보겠습니다.
```
with open("example.txt", "w") as f:
    f.write("Keep Calm and Code Python")
```
f.open, f.close를 따로 써줄 필요 없이 with 키워드로 이렇게 작성해줄 수도 있습니다.

13. try ~ expect, finally(예외 처리)

Python에서 예외 처리를 하는 방법을 알아보겠습니다.

먼저 예외가 발생할 수 있는 부분을 try 문으로 묶은 다음에  
except문으로 예외를 지정해서 처리해줄 수 있습니다. 다음 코드를 보겠습니다.
```
try:
    num = 10 / 0
    print(num)
except Exception:
    print("0으로 나눌 수 없습니다.")
```
이 코드를 실행하게 되면 except 문만 실행되는 것을 알 수 있습니다.  
10을 0으로 나눌 때 오류가 발생해서 except 문으로 넘어갔기 때문에  
print(num) 부분은 실행되지 않습니다.

만약에 위의 코드에서 0이 아닌 5로 나누었다면 어떤 결과가 나올까요?
```
try:
    num = 10 / 5
    print(num)
except Exception:
    print("0으로 나눌 수 없습니다.")
```
이 코드를 실행하게 되면 2.0 이 나올 것입니다.  
except 문이 아닌 try 부분만 실행됨을 알 수 있습니다.

그리고 except 문에 Exception이 아닌 좀 더 명확한  
예외를 표기할 수도 있습니다. 예를 들면 이런 식이죠.
```
try:
    num = 10 / 0
    print(num)
except ZeroDivisionError as e:
    print("0으로 나눌 수 없습니다.")
```
바뀐 부분이 두 가지 있습니다. except 문에  
Exception이 아닌 ZeroDivisionError 로 명시한 것과   
as e 라는 것을 추가한 것입니다.   
또한 except (ZeroDivisionError, IndexError) as e: 처럼  
() 로 묶어서 함께 처리하는 것도 가능합니다.

as e 부분은 말 그대로 alias e 라는 뜻으로   
except 문 안에서 ZeroDivisionError 라는 이름을 e 라는  
이름으로 쓰겠다는 말입니다.   
그리고 ZeroDivisionError 는 Exception 중에 하나로 0으로  
나눌 경우 발생하는 에러입니다.

ZeroDivisionError 는 Exception 클래스를 상속받기 때문에  
Exception으로 호출해도 불리게 됩니다.

그 다음에는 finally 키워드에 대해 알아보겠습니다.

finally 키워드는 예외가 발생하든 안하든 무조건 실행시킬 코드입니다.
```
try:
    num = 10 / 5
    print(num)
except ZeroDivisionError as e:
    print('0으로 나눌 수 없습니다.')
finally:
    print('실행 완료')
```
라고 코드를 적게 될 경우 2.0이 출력된 후, 실행 완료가 출력됩니다.
```
try:
    num = 10 / 0
    print(num)
except ZeroDivisionError as e:
    print('0으로 나눌 수 없습니다.')
finally:
    print('실행 완료')
```
이 경우에도 except 문이 실행된 후에 실행 완료 가 출력됩니다.

Exception에 종류에는 다양한 것들이 있으므로   
때에 맞춰서 다양한 Exception 클래스를 사용할 수 있습니다.   
그리고 Exception 클래스를 상속받아서 자신만의 클래스를 정의해서 사용할 수도 있습니다.

그리고 try 문에서 raise 키워드를 사용해서 사용자가  
직접 오류를 발생시키는 것 또한 가능합니다.
```
class CustomError(Exception):
    def __str__(self):
        return "올바르지 않은 이름입니다."

def say_hello(name):
    if name == 'Leopold':
        print('Hello!')
    else:
        raise CustomError()

try:
    say_hello('Leopold')
    say_hello('myungseo')
except CustomError as e:
    print(e)
```
이런 식으로 raise, CustomError 를 모두 사용해보았습니다.  
그리고 str 함수 같은 경우에는 더블언더바 함수라고 하는 특정한  
용도로 미리 정의해둔 함수입니다.

